version: "3.7"
networks:
  default:
    name: clean-node-api
services:
  database:
    container_name: clean-node-api-database
    image: mongo:5.0.9
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: clean-node-api
      MONGO_INITDB_ROOT_PASSWORD: clean-node-api
  server:
    container_name: clean-node-api-server
    image: node:16-alpine
    working_dir: /usr/clean-node-api
    restart: always
    command: sh -c "npm install --force --silent && npm run build && npm run debug"
    ports:
      - 5050:5050
      - 9222:9222
    volumes:
      - ./:/usr/clean-node-api/
      # No curso é mapeada apenas a pasta 'dist' mas creio ter mais sentido fazer essa filtragem apenas no momento do deploy
      # - ./dist/:/usr/clean-node-api/dist/
      # - ./package.json:/usr/clean-node-api/package.json
    depends_on:
      - database