version: "3.7"
networks:
  default:
    name: clean-node-api
services:
  database:
    container_name: clean-node-api-database
    image: mongo:5.0.9
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: clean-node-api
      MONGO_INITDB_ROOT_PASSWORD: clean-node-api
  server:
    container_name: clean-node-api-server
    build: .
    image: clean-node-api
    restart: always
    command: npm run debug
    ports:
      - 5050:5050
      - 9222:9222
    volumes:
      - ./dist:/usr/clean-node-api/dist
      - ./package.json:/usr/clean-node-api/package.json
    depends_on:
      - database